# Manifest-only formula for the binary-only cargo-refine distribution
# (Proposal 003). Generated by the release pipeline — do not edit by hand.
class CargoRefine < Formula
  desc "Modelless code healer: clippy, rust perf, kernel, docker, rustc-error fixes"
  homepage "https://github.com/gist-rs/cargo-refine"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gist-rs/cargo-refine/releases/download/v0.2.0/cargo-refine-v0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "7cfdd7488c2835f655eeb81a31e423d64cf3e387cdae1627396c6f69b4e6fc43"
    else
      url "https://github.com/gist-rs/cargo-refine/releases/download/v0.2.0/cargo-refine-v0.2.0-x86_64-apple-darwin.tar.gz"
      sha256 "af3219a8e12076821509472d3d7e5a0b59ab917a74a03106e1ad8441a81a7e15"
    end
  end
  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/gist-rs/cargo-refine/releases/download/v0.2.0/cargo-refine-v0.2.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "c16d1de618c5bb89e96e894b75f520cc44a164b36549582c3ea36966ec0e60e2"
    else
      url "https://github.com/gist-rs/cargo-refine/releases/download/v0.2.0/cargo-refine-v0.2.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "42d8be0930ee658fa9a8e83647b297fc22d6f2763a842776fc9d1a3d4f6dd0a3"
    end
  end

  def install
    bin.install "cargo-refine"
  end
end
