# Manifest-only formula for the binary-only cargo-heal distribution
# (Proposal 003). Generated by the release pipeline — do not edit by hand.
class CargoHeal < Formula
  desc "Modelless code healer: clippy, rust perf, kernel, docker, rustc-error fixes"
  homepage "https://github.com/gist-rs/cargo-heal"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gist-rs/cargo-heal/releases/download/v0.1.3/cargo-heal-v0.1.3-aarch64-apple-darwin.tar.gz"
      sha256 "04801e439ab2fe17274407cae846f48b27f0b15b69da9fb37af4c7d142ef0bd6"
    else
      url "https://github.com/gist-rs/cargo-heal/releases/download/v0.1.3/cargo-heal-v0.1.3-x86_64-apple-darwin.tar.gz"
      sha256 "ecdab40a0aab326ef487c821941b364c7539fa38e73998f2f73de05baf39a7f4"
    end
  end
  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/gist-rs/cargo-heal/releases/download/v0.1.3/cargo-heal-v0.1.3-aarch64-unknown-linux-musl.tar.gz"
      sha256 "44876bea4c74b37ac044581fe50bd21be9e41a0e448e54206fc87ec7a17062d5"
    else
      url "https://github.com/gist-rs/cargo-heal/releases/download/v0.1.3/cargo-heal-v0.1.3-x86_64-unknown-linux-musl.tar.gz"
      sha256 "195b1f263c99ddbdcc76882b6385a027694d198676a4cf9e294a6c34b934741b"
    end
  end

  def install
    bin.install "cargo-heal"
  end
end
