# Manifest-only formula for the binary-only cargo-heal distribution
# (Proposal 003). Generated by the release pipeline — do not edit by hand.
class CargoHeal < Formula
  desc "Modelless code healer: clippy, rust perf, kernel, docker, rustc-error fixes"
  homepage "https://github.com/gist-rs/cargo-heal"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gist-rs/cargo-heal/releases/download/v0.1.4/cargo-heal-v0.1.4-aarch64-apple-darwin.tar.gz"
      sha256 "a6965b525f8ae9df3296c51fc62afe6e5639210197e65ef178b86c66dc5109a5"
    else
      url "https://github.com/gist-rs/cargo-heal/releases/download/v0.1.4/cargo-heal-v0.1.4-x86_64-apple-darwin.tar.gz"
      sha256 "f5faaee297f1734aa338288dfec83eedaf5d56dfbaa8b8deb879d5730c6e3469"
    end
  end
  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/gist-rs/cargo-heal/releases/download/v0.1.4/cargo-heal-v0.1.4-aarch64-unknown-linux-musl.tar.gz"
      sha256 "23a2df1a72b6959b3e4c550d7739a52194b166d7b7e285444bb4d23635a8ae0d"
    else
      url "https://github.com/gist-rs/cargo-heal/releases/download/v0.1.4/cargo-heal-v0.1.4-x86_64-unknown-linux-musl.tar.gz"
      sha256 "747fbd8a7acf427b3f79b261eb7a663f9f942c9213953447649ed6b883da4d46"
    end
  end

  def install
    bin.install "cargo-heal"
  end
end
