# Manifest-only formula for the binary-only cargo-heal distribution
# (Proposal 003). Generated by the release pipeline — do not edit by hand.
class CargoHeal < Formula
  desc "Modelless code healer: clippy, rust perf, kernel, docker, rustc-error fixes"
  homepage "https://github.com/gist-rs/cargo-heal"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gist-rs/cargo-heal/releases/download/v0.1.1/cargo-heal-v0.1.1-aarch64-apple-darwin.tar.gz"
      sha256 "287fa077e422e7373d2c534698afcbb88b331c899c4be318eeaaad88c016a952"
    else
      url "https://github.com/gist-rs/cargo-heal/releases/download/v0.1.1/cargo-heal-v0.1.1-x86_64-apple-darwin.tar.gz"
      sha256 "9fd84e497e9c1924df7b9e5583d422ca32d8995d6f754fce718572863e7f1701"
    end
  end
  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/gist-rs/cargo-heal/releases/download/v0.1.1/cargo-heal-v0.1.1-aarch64-unknown-linux-musl.tar.gz"
      sha256 "78e2fd31e3022cfb325e36b1438b5faef9c8c5d575c05d4e3db392f65bfa2a2e"
    else
      url "https://github.com/gist-rs/cargo-heal/releases/download/v0.1.1/cargo-heal-v0.1.1-x86_64-unknown-linux-musl.tar.gz"
      sha256 "062bc3ea659a68b648094c42b128970b9c085143d0d41019522968d7980b8642"
    end
  end

  def install
    bin.install "cargo-heal"
  end
end
